### ISSUE TITLE
Unable to read file at

### ISSUE THREAD

**Issue by RuizuKun-Dev** [filiptibell/roblox-place-publish-action#1]
![image](https://user-images.githubusercontent.com/55673217/159865148-5c4845ef-36aa-4255-b05b-89cd4a5cb2c3.png)
![image](https://user-images.githubusercontent.com/55673217/159865238-5a413d4b-244d-4585-9fb8-126bece02174.png)

Not sure why it's not working

**Comment by filiptibell** [comment]
Seems like you forgot to check out (download) your repository inside of your workflow. This means that inside of the workflow, none of the files in your repository will be available, so the `Unable to read file at ""` message in this case means that the file simply doesn't exist. I'll look into making the error message clearer if something like this happens.

To check out your repository inside of your workflow and have your files available to use, you should put in a step with [the official checkout action](https://github.com/actions/checkout) before running the publish. Hope that helps!

**Comment by RuizuKun-Dev** [comment]
@filiptibell would this be correct?

```yml
name: Roblox Unit Test

on: [push]

jobs:
  Run-Tests:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v1

      - name: Install Tools
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Roblox Studio
        uses: OrbitalOwen/roblox-win-installer-action@1.1
        with:
          cookie: ${{ secrets.ROBLOXSECURITY }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add RBXID to the Windows registry
        run: REG ADD HKCU\Software\RobloxStudioBrowser\roblox.com /t REG_SZ /v .RBXID /d "${{ secrets.RBXID }}"

      # Flip flag that causes issue
      - name: Create fflag overrides
        run: |
          $flags = @{DFIntStudioUseNewLoginDataEndpointHundredthPercent=0; FFlagStudioUseNewLoginDataEndpoint=$false}
          New-Item -Path 'C:/Program Files (x86)/Roblox/Versions/version-*/' -Name "ClientSettings" -ItemType "directory"
          New-Item -Path 'C:/Program Files (x86)/Roblox/Versions/version-*/ClientSettings' -Name "ClientAppSettings.json"
          $flags | ConvertTo-Json -depth 32| set-content -Path 'C:/Program Files (x86)/Roblox/Versions/version-*/ClientSettings/ClientAppSettings.json'

      - name: Run tests
        run: |
          run-in-roblox --place "./Time Attack!.rbxlx" --script ./src/TestService/TestServer/init.lua
          run-in-roblox --place "./Time Attack!.rbxlx" --script ./src/TestService/TestClient/init.lua

      - name: Publish to Roblox
        uses: filiptibell/roblox-place-publish-action@v2.1
        with:
          universe-id: "3166878368"
          place-id: "8255321900"
          api-key: ${{ secrets.CLOUD_API_KEY }}
          path: "Time Attack!.rbxl"

      - name: Publish to Roblox
        uses: Ulferno/upload-to-roblox@latest
        with:
          api-key: ${{ secrets.ROBLOX_API_KEY }}
          universeId: 3166878368
          placeId: 8255321900
          file: "./Time Attack!.rbxl"
```
