### ISSUE TITLE
Unable to read file at "src/place.rbxl"

### ISSUE THREAD

**Issue by Krultu** [filiptibell/roblox-place-publish-action#2]
Hi,
I'm trying to use your action, but I can't find a way to do it successfully.

Here's YML file:

```
name: Publish Roblox Place

on: push

jobs:
  Deploy:
    runs-on: windows-latest

    steps:
      - uses: filiptibell/roblox-place-publish-action@v2.1
        with:
          universe-id: 'myUniverseId'
          place-id: 'myPlaceId'
          api-key: ${{ secrets.CLOUD_API_KEY }}
          path: 'src/place.rbxl'
          max-retries: '1'
```
![image](https://user-images.githubusercontent.com/76265885/178167685-940fb94b-738a-4e2b-89e6-270acbb78574.png)
![image](https://user-images.githubusercontent.com/76265885/178167704-5ed33b7f-8c2d-418e-8551-65ae8ab2ae14.png)
![image](https://user-images.githubusercontent.com/76265885/178167730-5555fbff-ef81-4b8f-a817-72e1de030916.png)

I'm new to Github, sorry
