### ISSUE TITLE
Error 401: Unauthorized

### ISSUE THREAD

**Issue by Krultu** [filiptibell/roblox-place-publish-action#3]
Hi,
I tried your action, but I'm getting error 401.

![image](https://user-images.githubusercontent.com/76265885/178169054-acf36869-dd4b-4df2-b013-a746fea8fb36.png)

Here's my YML file:
```
name: Publish Roblox Place

on: push

jobs:
  Deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - uses: filiptibell/roblox-place-publish-action@v2.1
        with:
          universe-id: 'myUniverseId'
          place-id: 'myPlaceId'
          api-key: ${{ secrets.CLOUD_API_KEY }}
          path: 'src/place.rbxl'
          max-retries: '3'
```

And yes, I have created the action secret
![image](https://user-images.githubusercontent.com/76265885/178169139-6628635a-1c8f-4b57-acc2-b3a8390af0fc.png)
